{% set version = "8.3" %}
{% set name = "sagelib" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sagemath/sage/archive/{{ version }}.tar.gz
  sha256: 41fd0b4eb820f7a1274e12294b6fbdbbf60d0027bff98c22fdc84da140964929
  patches:
    # sage patches cython to include sys.path, workaround that
    - patches/Fix-cython-bug.patch
    # don't do sanity checks as we are not in a source build
    - patches/sage-env.patch
    # disable sage-location since conda handles that and sage-location breaks
    # conda scripts
    - patches/disable-sage-location.patch
    # mostly remove SPKG interface until we have #20382 (Sage 8.3)
    - patches/0006-no-spkg-doctest.patch
    # fix too long file name
    - patches/fix_cache_file_length.patch
    # undo upgrade to an unreleased PARI
    - patches/use-sages-ratpoints.patch
    # fix a compile error with c++11
    - patches/0007-drop-struct-keyword.patch
    # compatibility with cddlib 0.94j so we can use gfan
    - patches/cddlib-094j.patch
    # upgrade to sympy as we ship that version in conda-forge 1.2
    - patches/sympy-12.patch

build:
  number: 2
  skip: true  # [win]
  skip: true  # [py3k and py<36]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - libtool
    - automake
  host:
    - {{ compiler('cxx') }}

  host:
    - pip
    - setuptools
    - arb 2.13.*
    - blas 1.1 {{ variant }}
    - openblas
    - brial 1.2.*
    - cliquer 1.21
    - cypari2 >=1.1.4
    - cysignals 1.7.*
    - cython >=0.28.2
    - ecl 16.1.*
    - eclib >=20171002
    - ecm 7.*
    - future
    - glpk
    - gmp
    - gsl
    - iml 1.0.*
    - jinja2 2.10.*
    - jupyter_core 4.*
    - lcalc 1.23
    - lrcalc 1.2
    - libflint 2.5.*
    - libgap 4.8.6
    - libgd 2.2.*
    - libpng
    - linbox 1.5.*
    - givaro
    - fflas-ffpack
    - m4ri >=20140914
    - m4rie >=20150908
    - mpc 1.1.*
    - mpfi 1.5.*
    - mpfr
    - ntl
    - {{ pin_compatible('numpy') }}
    - pari 2.9.5
    - pkgconfig
    - planarity 3.*
    - ppl 1.2
    - pynac 0.7.22
    - python
    - ratpoints 2.1.*
    - readline
    - rw 0.7
    - singular 4.1.*
    - six
    - symmetrica 2.0
    - zlib
    - zn_poly 0.9
    # sageruntime deps
    - ipython >=5
    - psutil >=5
    - pexpect >=4

  # We can not include all actual runtime dependencies of Sage here as some of
  # them require Sage to build, such as some of the database packages.
  # The packages listed here are taken from the `SAGERUNTIME` variable in
  # `build/make/Makefile`.
  # These dependencies are enough to `import sage` and start `sage` but lots of
  # things do not work. To get all the standard dependencies of Sage, install
  # the "sage" package (which requires this "sagelib" package.)
  run:
    - arb 2.13.*
    - blas 1.1 {{ variant }}
    - openblas
    - brial 1.2.*
    - cliquer 1.21
    - cypari2 1.1.4
    - cysignals 1.7.*
    - cython >=0.28.2
    - ecl 16.1.*
    - eclib >=20171002
    - ecm 7.*
    - future
    - glpk
    - gmp
    - gsl
    - iml 1.0.*
    - jinja2 2.10.*
    - jupyter_core 4.*
    - lcalc 1.23
    - lrcalc 1.2
    - libflint 2.5.*
    - libgap 4.8.6
    - libgd 2.2.*
    - libpng
    - linbox 1.5.*
    - givaro
    - fflas-ffpack
    - matplotlib
    - m4ri >=20140914
    - m4rie >=20150908
    - mpc 1.1.*
    - mpfi 1.5.*
    - mpfr
    - ntl
    - {{ pin_compatible('numpy') }}
    - pari 2.9.5
    - pkgconfig
    - planarity 3.*
    - ppl 1.2
    - pynac 0.7.22
    - python
    - ratpoints 2.1.*
    - readline
    - rw 0.7
    - singular 4.1.*
    - six
    - symmetrica 2.0
    - zlib
    - zn_poly 0.9
    # sageruntime deps
    - ipython >=5
    - psutil >=5
    - pexpect >=4

test:
  requires:
    # Sage's doctesting framework uses a pretty printing command from sympy
    - sympy
  source_files:
    - src/sage/version.py
  imports:
    - sage
  commands:
    - sage -v
    - sage -c 1+1
    # too many doctests fail still but we test that the doctesting framework works by testing a trivial file
    - sage -tp src/sage/version.py

about:
  home: https://www.sagemath.org
  license: GPLv2+
  license_file: COPYING.txt
  summary: Open Source Mathematical Software
  dev_url: https://trac.sagemath.org
  doc_url: https://doc.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
