{% set version = "8.8.rc1" %}
{% set name = "sagelib" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sagemath/sage/archive/{{ version }}.tar.gz
  sha256: 7cd194e15bb4238bd17e085e3b406954823f40e540d6662fb357ba2d785fc013
  patches:
    - patches/0006-no-spkg-doctest.patch
    # don't do sanity checks as we are not in a source build
    - patches/sage-env.patch
    # disable sage-location since conda handles that and sage-location breaks
    # conda scripts
    - patches/disable-sage-location.patch
    # fix too long file name
    - patches/fix_cache_file_length.patch
    - patches/26932.diff

build:
  number: 1
  skip: true  # [win]
  skip: true  # [py3k and py<36]

requirements:
  build:
    - libtool
    - automake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - pip
    - setuptools
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - arb           2.16.*
    - brial         1.2.*
    - libbrial      1.2.*
    - cliquer       1.21.*
    - cypari2       2.1.*
    - cysignals     1.10.*
    - cython        0.29.*
    # There are issues with ecl 16.1.3
    - ecl           16.1.2
    - eclib         20190226
    - ecm           7.*
    - future
    - gap-core      4.10.*
    - glpk
    - gmp
    - gmpy2         2.1.*
    - gsl
    - iml           1.0.*
    - jinja2        2.10.*
    - jupyter_core  4.*
    - lcalc         1.23
    - lrcalc        1.2
    - libbraiding   1.0
    - libflint      2.5.*
    - libgd         2.2.*
    - libhomfly     1.02.*
    - libpng
    - linbox        1.6.*
    - givaro
    - fflas-ffpack
    - m4ri          20140914
    - m4rie         20150908
    - mpc           1.1.*
    - mpfi          1.5.*
    - mpfr
    - ntl
    - numpy
    - pari
    - pkgconfig
    - pkg-config
    - planarity     3.*
    - ppl           1.2
    - pplpy         0.8.*
    - pynac         0.7.25
    - python
    - ratpoints     2.1.*
    - readline
    - rw            0.7
    - singular
    - six
    - symmetrica    2.0
    - zlib
    - zn_poly       0.9.*
    # sageruntime deps
    - ipython       >=5,<6
    - psutil        >=5
    - pexpect       >=4

  # We can not include all actual runtime dependencies of Sage here as some of
  # them require Sage to build, such as some of the database packages.
  # The packages listed here are taken from the `SAGERUNTIME` variable in
  # `build/make/Makefile`.
  # These dependencies are enough to `import sage` and start `sage` but lots of
  # things do not work. To get all the standard dependencies of Sage, install
  # the "sage" package (which requires this "sagelib" package.)
  run:
    - arb
    - {{ pin_compatible("libbrial", max_pin="x.x") }}
    - {{ pin_compatible("cliquer", max_pin="x.x") }}
    - {{ pin_compatible("cypari2") }}
    - {{ pin_compatible("cysignals") }}
    - {{ pin_compatible("cython") }}
    - {{ pin_compatible("ecl", max_pin="x.x") }}
    - eclib
    - {{ pin_compatible("ecm") }}
    - future
    - {{ pin_compatible("gap-core", max_pin="x.x") }}
    - glpk
    - gmp
    - {{ pin_compatible("gmpy2", max_pin="x.x") }}
    - gsl
    - {{ pin_compatible("iml", max_pin="x.x") }}
    - {{ pin_compatible("jinja2", max_pin="x.x") }}
    - {{ pin_compatible("jupyter_core") }}
    - {{ pin_compatible("lcalc", max_pin="x.x") }}
    - {{ pin_compatible("lrcalc", max_pin="x.x") }}
    - {{ pin_compatible("libbraiding", max_pin="x.x") }}
    - {{ pin_compatible("libflint", max_pin="x.x") }}
    - {{ pin_compatible("libgd", max_pin="x.x") }}
    - {{ pin_compatible("libhomfly", max_pin="x.x") }}
    - libpng
    - {{ pin_compatible("linbox", max_pin="x.x") }}
    - givaro
    - fflas-ffpack
    - matplotlib
    - m4ri
    - {{ pin_compatible("m4rie") }}
    - mpc
    - mpfi
    - mpfr
    - ntl
    - {{ pin_compatible("numpy") }}
    - pari
    - pkgconfig
    - {{ pin_compatible("planarity") }}
    - {{ pin_compatible("ppl", max_pin="x.x") }}
    - {{ pin_compatible("pplpy", max_pin="x.x") }}
    - {{ pin_compatible("pynac", max_pin="x.x.x") }}
    - python
    - {{ pin_compatible("ratpoints", max_pin="x.x") }}
    - readline
    - {{ pin_compatible("rw", max_pin="x.x") }}
    - singular
    - six
    - {{ pin_compatible("symmetrica", max_pin="x.x") }}
    - zlib
    - {{ pin_compatible("zn_poly", max_pin="x.x") }}
    # sageruntime deps
    - ipython       >=5,<6
    - psutil        >=5
    - pexpect       >=4

test:
  requires:
    # Sage's doctesting framework uses a pretty printing command from sympy
    - sympy
    - ipywidgets
  source_files:
    - src/sage/version.py
  imports:
    - sage
  commands:
    - sage -v
    - sage -c 1+1
    # too many doctests fail still but we test that the doctesting framework works by testing a trivial file
    - sage -tp src/sage/version.py

about:
  home: https://www.sagemath.org
  license: GPLv2+
  license_file: COPYING.txt
  summary: Open Source Mathematical Software
  dev_url: https://trac.sagemath.org
  doc_url: https://doc.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
