{% set version = "9.5" %}
{% set name = "sagelib" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sagemath/sage/archive/{{ version }}.tar.gz
  sha256: 8d70a3b26080802c5b2e33dda4c23795d494d8216a0c2ecfcd608ebab0e64ff6
  patches:  # [build_platform != target_platform]
  - singular.patch  # [build_platform != target_platform]

build:
  number: 1
  skip: true  # [win]
  skip: true  # [py3k and py<37]
  ignore_run_exports_from:
    - {{ compiler('fortran') }}

requirements:
  build:
    - libtool
    - automake
    - m4
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - pkg-config
    - gettext
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - memory-allocator                       # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - pip
    - setuptools
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - arb
    - boost-cpp
    - brial         1.2.*
    - libbrial      1.2.*
    - cliquer       1.22.*
    - cypari2       2.1.*
    - cysignals     1.11.*
    - cython
    - ecl           21.2.*
    - eclib         20210625
    - ecm           7.*
    - future
    - gap-core      4.11.1
    - giac          1.6.*
    - glpk
    - gmp
    - gmpy2         2.1.*
    - gsl
    - iml           1.0.*
    - jinja2        3.0.*
    - jupyter_core  4.*
    - lcalc         2.0.*
    - lrcalc        1.2
    - libbraiding   1.1
    - libflint
    - libflint      * *_ntl_*
    - libgd         2.3.*
    - libhomfly     1.02.*
    - libpng
    - linbox        >=1.6.3
    - givaro        4.1.*
    - fflas-ffpack  2.4.*
    - m4ri
    - m4rie
    - memory-allocator
    - mpc           1.2.*
    - mpfi          1.5.*
    - mpfr
    - ntl
    - numpy
    - pari
    - pkgconfig
    - pkg-config
    - planarity     3.*
    - ppl           1.2
    - pplpy         0.8.*
    - pynac         0.7.29
    - python
    - ratpoints     2.1.*
    - readline
    - rw            0.9
    - singular
    - six
    - symmetrica    2.0
    - zlib
    - zn_poly       0.9.*
    # sageruntime deps
    - ipython       >=7.29,<8
    - psutil        >=5.2
    - pexpect       >=4.8.0,<5
    # for the symlinks
    - three.js
    - notebook      >=6.4.6,<7
    - jmol          >=14.29.52,<15

  # We can not include all actual runtime dependencies of Sage here as some of
  # them require Sage to build, such as some of the database packages.
  # The packages listed here are taken from the `SAGERUNTIME` variable in
  # `build/make/Makefile`.
  # These dependencies are enough to `import sage` and start `sage` but lots of
  # things do not work. To get all the standard dependencies of Sage, install
  # the "sage" package (which requires this "sagelib" package.)
  run:
    - {{ pin_compatible("libbrial", max_pin="x.x") }}
    - {{ pin_compatible("cliquer", max_pin="x.x") }}
    - {{ pin_compatible("cypari2") }}
    - {{ pin_compatible("cysignals") }}
    - {{ pin_compatible("cython") }}
    - {{ pin_compatible("ecl", max_pin="x.x") }}
    - eclib
    - {{ pin_compatible("ecm") }}
    - future
    - {{ pin_compatible("gap-core", max_pin="x.x") }}
    - {{ pin_compatible("giac", max_pin="x.x") }}
    - glpk
    - gmp
    - {{ pin_compatible("gmpy2", max_pin="x.x") }}
    - gsl
    - {{ pin_compatible("iml", max_pin="x.x") }}
    - {{ pin_compatible("jinja2", max_pin="x.x") }}
    - {{ pin_compatible("jupyter_core") }}
    - {{ pin_compatible("lcalc", max_pin="x.x") }}
    - {{ pin_compatible("lrcalc", max_pin="x.x") }}
    - {{ pin_compatible("libbraiding", max_pin="x.x") }}
    - {{ pin_compatible("libflint", max_pin="x.x") }}
    - libflint
    - libflint      * *_ntl_*
    - {{ pin_compatible("libgd", max_pin="x.x") }}
    - {{ pin_compatible("libhomfly", max_pin="x.x") }}
    - libpng
    - {{ pin_compatible("linbox", max_pin="x.x") }}
    - givaro
    - fflas-ffpack
    - {{ pin_compatible("m4ri") }}
    - {{ pin_compatible("m4rie") }}
    - memory-allocator
    - mpc
    - mpfi
    - mpfr
    - ntl
    - {{ pin_compatible("numpy") }}
    - pari
    - {{ pin_compatible("planarity") }}
    - {{ pin_compatible("ppl", max_pin="x.x") }}
    - {{ pin_compatible("pplpy", max_pin="x.x") }}
    - primecountpy
    - {{ pin_compatible("pynac", max_pin="x.x.x") }}
    - python
    - {{ pin_compatible("ratpoints", max_pin="x.x") }}
    - readline
    - {{ pin_compatible("rw", max_pin="x.x") }}
    - singular
    - six
    - {{ pin_compatible("symmetrica", max_pin="x.x") }}
    - zlib
    - {{ pin_compatible("zn_poly", max_pin="x.x") }}
    # sageruntime deps
    - ipython       >=7.29,<8
    - psutil        >=5.2
    - pexpect       >=4.8.0,<5
  run_constrained:
    - {{ pin_compatible("three.js") }}

test:
  requires:
    # Sage's doctesting framework uses a pretty printing command from sympy
    - sympy
    - ipywidgets
    - pip
  source_files:
    - src/sage/version.py
  imports:
    - sage
  commands:
    - sage -v
    - sage -c 1+1
    # too many doctests fail still but we test that the doctesting framework works by testing a trivial file
    - sage -tp src/sage/version.py

about:
  home: https://www.sagemath.org
  license: GPL-2.0-or-later
  license_file: COPYING.txt
  summary: Open Source Mathematical Software
  dev_url: https://trac.sagemath.org
  doc_url: https://doc.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
