{% set version = "8.2rc4" %}
{% set name = "sagelib" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sagemath/sage/archive/{{ version }}.tar.gz
  sha256: a42b55c2c8ac244535dc9b87171b7d4dd7e1d498099518ab253354fbe2eaaa7b
  patches:
    # sage patches cython to include sys.path, workaround that
    - patches/Fix-cython-bug.patch
    # don't do sanity checks as we are not in a source build
    - patches/sage-env.patch
    # disable sage-location since conda handles that and sage-location breaks
    # conda scripts
    - patches/disable-sage-location.patch
    # fix cython errors
    - patches/0001-Map._extra_slots-do-not-pass-dict.patch
    - patches/0002-Various-Cython-fixes.patch
    # fix pynac interface changes
    - patches/0003-remove-superfluous-interface.patch
    - patches/0004-24411-adapt-to-pynac-0.7.14.patch
    - patches/0005-changes-to-interface.patch

build:
  number: 1
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - libtool
    - automake
    - pip
    - setuptools
    - arb 2.13.*
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - brial 1.2.*
    - cliquer 1.21
    - cypari2 >=1.1.4
    - cysignals 1.7.*
    - cython >=0.28
    - ecl 16.1.*
    - eclib >=20171002
    - ecm 7.*
    - future
    - givaro 4.0.*
    - glpk 4.65.*
    - gmp >=5.0.1,<7
    - gsl 2.4.*
    - iml 1.0.*
    - jinja2 2.10.*
    - jupyter_core 4.*
    - lcalc 1.23
    - lrcalc 1.2
    - libflint 2.5.*
    - libgap 4.8.6
    - libgd 2.2.*
    - libpng >=1.6.29,<1.7
    - linbox 1.5.*
    - m4ri >=20140914
    - m4rie >=20150908
    - mpc 1.1.*
    - mpfi 1.5.*
    - mpfr 4.*
    - ntl 10.3.*
    - numpy 1.13.*
    - pari 2.9.*
    - pkgconfig
    - planarity 3.*
    - ppl 1.2
    - pynac 0.7.17
    - python
    - ratpoints 2.1.*
    - readline 6.2*
    - rw 0.7
    - singular 4.1.*
    - six
    - symmetrica 2.0
    - zn_poly 0.9
    # sageruntime deps
    - ipython >=5
    - psutil >=5
    - pexpect >=4

  # We can not include all actual runtime dependencies of Sage here as some of
  # them require Sage to build, such as some of the database packages.
  # The packages listed here are taken from the `SAGERUNTIME` variable in
  # `build/make/Makefile`.
  # These dependencies are enough to `import sage` and start `sage` but lots of
  # things do not work. To get all the standard dependencies of Sage, install
  # the "sage" package (which requires this "sagelib" package.)
  run:
    - arb 2.13.*
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - brial 1.2.*
    - cliquer 1.21
    - cypari2 1.1.4
    - cysignals 1.7.*
    - cython >=0.28
    - ecl 16.1.*
    - eclib >=20171002
    - ecm 7.*
    - future
    - givaro 4.0.*
    - glpk 4.65.*
    - gmp >=5.0.1,<7
    - gsl 2.4.*
    - iml 1.0.*
    - jinja2 2.10.*
    - jupyter_core 4.*
    - lcalc 1.23
    - lrcalc 1.2
    - libflint 2.5.*
    - libgap 4.8.6
    - libgd 2.2.*
    - libpng >=1.6.29,<1.7
    - linbox 1.5.*
    - m4ri >=20140914
    - m4rie >=20150908
    - mpc 1.1.*
    - mpfi 1.5.*
    - mpfr 4.*
    - ntl 10.3.*
    - numpy >=1.13
    - pari 2.9.*
    - pkgconfig
    - planarity 3.*
    - ppl 1.2
    - pynac 0.7.17
    - python
    - ratpoints 2.1.*
    - readline 6.2*
    - rw 0.7
    - singular 4.1.*
    - six
    - symmetrica 2.0
    - zn_poly 0.9
    # sageruntime deps
    - ipython >=5
    - psutil >=5
    - pexpect >=4

test:
  imports:
    - sage
  commands:
    - sage -v
    - sage -c 1+1

about:
  home: https://www.sagemath.org
  license: GPLv2+
  license_file: COPYING.txt
  summary: Open Source Mathematical Software
  dev_url: https://trac.sagemath.org
  doc_url: https://doc.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
