{% set version = "10.3" %}
{% set name = "sagelib" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sagemath/sage/archive/{{ version }}.tar.gz
  sha256: 59feb92c05e74d6db7a75f398c45c24b5157b1ecd3d8ac198806e2e6add77d96
  patches:
    - 0001-Build-glue-code-for-optional-extensions-sirocco-and-.patch
    - 0002-Do-not-cleanup-all-.so-files-when-cross-compiling.patch  # [build_platform != target_platform]
    # Do not use C++ symbols that have been removed in C++17.
    - 0001-src-sage-modular-arithgroup-farey.cpp-use-std-bind.patch

build:
  number: 2
  skip: true  # [win]
  skip: true  # [py<39]
  ignore_run_exports_from:
    - {{ compiler('fortran') }}
    # sagemath-standard needs sirocco at build time but only sagemath-sirocco
    # needs it at runtime
    - sirocco
    # sagemath-standard needs bliss at build time but only sagemath-bliss needs
    # it at runtime
    - bliss

requirements:
  build:
    - libtool
    - automake
    - m4
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - make
    - pkg-config
    - gettext
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3,<4                          # [build_platform != target_platform]
    - memory-allocator                       # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - pip
    - setuptools
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libboost-headers
    - brial         1.2.*
    - cliquer       1.22.*
    - cypari2       2.1.*
    - cysignals     1.11.*
    - cython        >=3,<4
    - ecl           >=21.2,<24
    - eclib
    - ecm           7.*
    - fflas-ffpack  2.4.*
    - future
    - gap-core      4.12.2
    - giac          1.9.*
    - givaro        4.1.*
    - glpk
    - gmp
    - gmpy2         >=2.1,<3
    - gsl
    - iml           1.0.*
    - jinja2        3.1.*
    - jupyter_core  >=5.3.2,<6
    - lcalc         2.0.*
    - libbraiding   1.2
    - libbrial      1.2.*
    # trying to merge the two folllowing lines into one doesn't work because of a
    # conda-build bug
    - libflint
    - libflint      * *_ntl_*
    - libgd         2.3.*
    - libhomfly     1.02.*
    - libpng
    - linbox        >=1.6.3
    - lrcalc        2.1
    - m4ri
    - m4rie
    - memory-allocator
    - mpc           1.*
    - mpfi          1.5.*
    - mpfr
    - ntl
    - numpy
    - pari
    - pkg-config
    - pkgconfig
    - planarity     3.*
    - ppl           1.2
    - pplpy         0.8.*
    - python
    - readline
    - rw            0.9
    - singular
    - six
    - symmetrica    3.0
    - zlib
    # sage runtime deps
    - ipython       >=8.18.1,<9
    - pexpect       >=4.9.0,<5
    # for the symlinks
    - threejs-sage
    - notebook      >=6.4.12,<7
    - jmol          >=14.29.52,<15

    # sagemath-standard needs bliss at build time but not at runtime, see sagemath-bliss
    - bliss >=0.77
    # sagemath-standard needs sirocco at build time but not at runtime, see sagemath-sirocco
    - sirocco

  # We can not include all actual runtime dependencies of Sage here as some of
  # them require Sage to build, such as some of the database packages.
  # The packages listed here are taken from the `SAGERUNTIME` variable in
  # `build/make/Makefile`.

  # These dependencies are enough to `import sage` and start `sage` but lots of
  # things do not work. To get all the standard dependencies of Sage, install
  # the "sage" package (which requires this "sagelib" package.)

  # By now we could probably drpo this separation and just use the new naming
  # from upstream, i.e., sagemath-standard, sagemath-bliss, sagemath-sirocco
  # and create one output called sage which would probably be an alias for
  # sagemath-standard. Until there is a sagemath-core or something like that,
  # we should probably keep sagelib around to be some minimal distribution.
  # See #169 for details.

  run:
    - {{ pin_compatible("cypari2") }}
    - {{ pin_compatible("cysignals") }}
    - {{ pin_compatible("cython") }}
    - {{ pin_compatible("ecl", max_pin="x.x") }}
    - future
    - {{ pin_compatible("gap-core", max_pin="x.x") }}
    - {{ pin_compatible("giac", max_pin="x.x") }}
    - {{ pin_compatible("gmpy2", max_pin="x.x") }}
    - {{ pin_compatible("jinja2", max_pin="x.x") }}
    - {{ pin_compatible("jupyter_core") }}
    - libflint  * *_ntl_*
    - memory-allocator
    - {{ pin_compatible("pplpy", max_pin="x.x") }}
    - primecountpy
    - python
    - six
    - {{ pin_compatible("pexpect") }}
    - python-lrcalc
    - {{ pin_compatible("threejs-sage") }}
    # Linbox has a run_exports but the version used in the build does not have it yet.
    - {{ pin_compatible("linbox", max_pin="x.x") }}
    # Disable ipython 8.19.0 which breaks the interactive session, see https://github.com/sagemath/sage/issues/36975
    - ipython >=8.4,<9,!=8.19.0

test:
  requires:
    # Sage's doctesting framework uses a pretty printing command from sympy
    - sympy
    - ipywidgets
    - pip
  source_files:
    - src/sage/version.py
  imports:
    - sage
  commands:
    - sage -v
    - sage -c 1+1
    # too many doctests fail still but we test that the doctesting framework works by testing a trivial file
    - sage -tp src/sage/version.py
    # Test that #135 has been resolved
    - sage -c 'import sage.modular.multiple_zeta'

outputs:
  - name: sagelib

  - name: sagemath-bliss
    script: install-sagemath-bliss.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython >=3,<4                          # [build_platform != target_platform]
        - memory-allocator                       # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - {{ pin_subpackage("sagelib", exact=True) }}
        - bliss >=0.77
        - python
        - numpy
        - memory-allocator
        - pip
        - pkg-config
        - pkgconfig
      run:
        - {{ pin_subpackage("sagelib", exact=True) }}
        # Since the ignore_run_exports_from apply globally to all outputs, we
        # need to explicitly require bliss here and cannot rely on its
        # run_exports.
        - {{ pin_compatible("bliss", max_pin="x.x") }}
        - python
    test:
      imports:
        - sage.graphs.bliss

  - name: sagemath-sirocco
    script: install-sagemath-sirocco.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython >=3,<4                          # [build_platform != target_platform]
        - memory-allocator                       # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - {{ pin_subpackage("sagelib", exact=True) }}
        - gmp
        - mpfr
        - sirocco
        - python
        - pip
        - numpy
        - memory-allocator
        - pkg-config
        - pkgconfig
      run:
        - {{ pin_subpackage("sagelib", exact=True) }}
        # Since the ignore_run_exports_from apply globally to all outputs, we
        # need to explicitly require sirocco here and cannot rely on its
        # run_exports.
        - {{ pin_compatible("sirocco") }}
        - python
    test:
      imports:
        - sage.libs.sirocco

about:
  home: https://www.sagemath.org
  license: GPL-2.0-or-later
  license_file: COPYING.txt
  summary: Open Source Mathematical Software
  dev_url: https://github.com/sagemath/sage
  doc_url: https://doc.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
    - alexjbest
