{% set version = "7.6" %}
{% set name = "sagelib" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sagemath/sage/archive/{{ version }}.tar.gz
  sha256: e6e0729ab25446e7c922058db0eee4b0b294b32c196e34842e843ea9fae41423
  patches:
    # sage patches cython to include sys.path, workaround that
    - patches/Fix-cython-bug.patch
    # sage's planarity is 2.x and conda-forge's is 3.x
    - patches/u1-version-planarity-3.patch
    # conda's python doesn't have a symlink from lib/python2.7 to lib/python
    - patches/sage-script.patch
    # don't do sanity checks as we are not in a source build
    - patches/sage-env.patch
    # disable sage-location since conda handles that and sage-location breaks
    # conda scripts
    - patches/disable-sage-location.patch

build:
  number: 1
  skip: true  # [win]
  skip: true  # [py!=27]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - ccache
    - libtool
    - automake
    - pip
    - setuptools
    - arb 2.9.*
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - brial 0.8.*
    - cliquer 1.21
    - cysignals 1.4.*
    - cython >=0.25
    - ecl 16.1.*
    - eclib >=20170330
    - ecm 7.*
    - future
    - givaro 4.0.*
    - glpk 4.61
    - gmp >=5.0.1,<7
    - gsl 2.2.*
    - iml 1.0.*
    - jinja2 2.9.*
    - jupyter_core >=4
    - lcalc 1.23
    - lrcalc 1.2
    - libflint 2.5.*
    - libgap 4.8.6
    - libgd 2.2.*
    - libpng >=1.6.28,<1.7
    - linbox 1.4.*
    - m4ri >=20140914
    - m4rie >=20150908
    - mpc 1.0.*
    - mpfi 1.5.*
    - mpfr 3.*
    - ntl 10.3.*
    - numpy 1.11.*
    - pari 2.9.*
    - pkgconfig
    - planarity 3.*
    - ppl 1.2
    - pynac 0.7.5
    - python
    - ratpoints 2.1.*
    - readline 6.2*
    - rw 0.7
    - singular 4.1.*
    - six
    - symmetrica 2.0
    - zn_poly 0.9
    # sageruntime deps
    - ipython >=5
    - psutil >=5
    - pexpect >=4

  run:
    - arb 2.9.*
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - brial 0.8.*
    - cliquer 1.21
    - cysignals 1.4.*
    - cython >=0.25
    - ecl 16.1.*
    - eclib >=20170330
    - ecm 7.*
    - future
    - givaro 4.0.*
    - glpk 4.61
    - gmp >=5.0.1,<7
    - gsl 2.2.*
    - iml 1.0.*
    - jinja2 2.9.*
    - jupyter_core >=4
    - lcalc 1.23
    - lrcalc 1.2
    - libflint 2.5.*
    - libgap 4.8.6
    - libgd 2.2.*
    - libpng >=1.6.28,<1.7
    - linbox 1.4.*
    - m4ri >=20140914
    - m4rie >=20150908
    - mpc 1.0.*
    - mpfi 1.5.*
    - mpfr 3.*
    - ntl 10.3.*
    - numpy 1.11.*
    - pari 2.9.*
    - pkgconfig
    - planarity 3.*
    - ppl 1.2
    - pynac 0.7.5
    - python
    - ratpoints 2.1.*
    - readline 6.2*
    - rw 0.7
    - singular 4.1.*
    - six
    - symmetrica 2.0
    - zn_poly 0.9
    # sageruntime deps
    - ipython >=5
    - psutil >=5
    - pexpect >=4

test:
  import:
    - sage
  commands:
    - sage -v

about:
  home: https://www.sagemath.org
  license: GPLv2+
  license_file: COPYING.txt
  summary: Open Source Mathematical Software
  dev_url: https://trac.sagemath.org
  doc_url: https://doc.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
