travis:
  secure:
    BINSTAR_TOKEN: a0KveO1LlVQkIvpTSiGcu/kQXTwjloeU7zcOspkESYygebZ+BGAF1t2oByXK9Mt7Ysh/2acnjivFXP5n8YHZGJSM0Qh1IvTRsNOH4+xS4pcio8oEyERm+w2htVWdPGGtpu6QTvZZrjGV0RYqelZrr07ddsOEGSlIvNAmh8aRpb/1+BZMkxWem3uVRXlrLraoqievbhTInp6MC/6fyS/v3S2yNjqjlyQpWCHXvOrsmAYZrbnmY7h1GUKxHh/3YFuPZmphhQr9X+uI8O/GpNQfwLsTm5haLEUjEd8B/Kos4K7NMr9WgmAYBKxWY41LmvhWjGasxk/n/XdeF58LFiXCIW43F9tsoSYcE45cwKguQoB8ca240eJQXbLEwGFhqopZr4nNlar+hFf3Vv0IdlwbCla+Ntqzsiwf46PIitNLwJVhwCJp/Zg/THjU3ZLd6gBMxYQfgbuMhhCM+EcGhzdQT3SNLYYC5jM/svu8q9fRBoarBpvwfr2dwvwQS7gIeSSos5G/GiqZ7qeLoTUllX+lp5S/4o1YX1gi/HVfPVTX4UDmRBA5XcjgWJiD3lB1sxvk2Wzfoe+BKsixmm8gTshVa6tJVvE9doiah/iDIV7UG4iBu4Mz9QC8AaAb/OxmY3n7tPuk0NhxbmvFuLqVfole1hBhjF+bSBXvbtgyKCCri0Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
